updates:
  - assignees:
      - daveio
    commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 100
    package-ecosystem: docker
    schedule:
      interval: daily
  - assignees:
      - daveio
    commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 100
    package-ecosystem: github-actions
    schedule:
      interval: daily
  - assignees:
      - daveio
    commit-message:
      include: scope
      prefix: chore
    directory: /
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies
    open-pull-requests-limit: 100
    package-ecosystem: gomod
    schedule:
      interval: daily
version: 2
