version: "2"
run:
  allow-parallel-runners: true
  concurrency: 4
linters:
  default: standard # all
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
issues:
  fix: false
