run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosec
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - errcheck
    - gosimple
    - stylecheck
    - typecheck
    - unused
    - revive
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
      - name: unexported-return
        disabled: true
  stylecheck:
    checks: ["all", "-ST1003"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - linters:
        - staticcheck
      text: "SA1019:"
