before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    # mod_timestamp: { { .CommitTimestamp } }
    targets:
      - go_first_class
changelog:
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - ^chore
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - order: 0
      regexp: ^.*feat[(\w)]*:+.*$
      title: New Features
    - order: 10
      regexp: ^.*fix[(\w)]*:+.*$
      title: Bug fixes
    - order: 999
      title: Other work
  sort: asc
  use: github
gomod:
  proxy: true
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2
