[env]
BELT_MISE_ACTIVE = 'true'

[settings]
env_file = '.env'
idiomatic_version_file = false
idiomatic_version_file_enable_tools = []


[tools]
go = { version = '1.24.4' }
'go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint' = { version = '2.1.6' }
'go:github.com/nametake/golangci-lint-langserver' = { version = '0.0.11' }

[tasks]
'claude' = { run = "bun x @anthropic-ai/claude-code", description = "Run the claude CLI command via bun" }
