jobs:
  dependabot-sync:
    secrets:
      gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    uses: charmbracelet/meta/.github/workflows/dependabot-sync.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
name: dependabot-sync
"on":
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch: null
permissions:
  contents: write
  pull-requests: write
