name: build
permissions: read-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21", "1.22", "1.23", "1.24"]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: cache
        uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: dependencies
        run: go mod download
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: coverage
        uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673 # v4.5.0
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
  platforms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21", "1.22", "1.23", "1.24"]
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: darwin-amd64
        run: GOOS=darwin GOARCH=amd64 go build -o hubbit-darwin-amd64 .
      - name: darwin-arm64
        run: GOOS=darwin GOARCH=arm64 go build -o hubbit-darwin-arm64 .
      - name: linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -o hubbit-linux-amd64 .
      - name: windows-amd64
        run: GOOS=windows GOARCH=amd64 go build -o hubbit-windows-amd64.exe .
