name: build
permissions: read-all
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{ matrix.go-version }}
      - name: cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: dependencies
        run: go mod download
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v -race ./...
  platforms:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{ matrix.go-version }}
      - name: darwin-amd64
        run: GOOS=darwin GOARCH=amd64 go build -o hubbit-darwin-amd64 .
      - name: darwin-arm64
        run: GOOS=darwin GOARCH=arm64 go build -o hubbit-darwin-arm64 .
      - name: linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -o hubbit-linux-amd64 .
      - name: windows-amd64
        run: GOOS=windows GOARCH=amd64 go build -o hubbit-windows-amd64.exe .
