name: check
permissions: read-all
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.24.3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3f6d2b9ad8fc00b7c64116213120aa014d8516c1
        with:
          version: latest
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: trivy
        uses: aquasecurity/trivy-action@26d71e622b84d103f86fb33a5a42c558e11f4ae0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
      - name: upload
        uses: github/codeql-action/upload-sarif@7b0fb5a4ac3b38ee6ee9a3ab6ffe59c27e9c4d3b
        with:
          sarif_file: trivy-results.sarif
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.24.3
      - name: gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not formatted:"
            gofmt -d .
            exit 1
          fi
      - name: tidy
        run: |
          go mod tidy
          if [ -n "$(git status --porcelain)" ]; then
            echo "go mod tidy would make changes:"
            git diff
            exit 1
          fi
