jobs:
  codacy:
    name: codacy
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: analysis
        uses: codacy/codacy-analysis-cli-action@09916000460adeeedc96b9704f86deba53e2ad5d
        with:
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          output: results.sarif
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
      - name: clean
        run: jq '.runs |= unique_by({tool, invocations, results})' < results.sarif > codacy.sarif
      - name: upload
        uses: github/codeql-action/upload-sarif@7b0fb5a4ac3b38ee6ee9a3ab6ffe59c27e9c4d3b
        with:
          sarif_file: codacy.sarif
name: codacy
on:
  pull_request: null
  push: null
permissions:
  actions: read
  contents: read
  security-events: write
