name: devskim
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  devskim:
    name: devskim
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - name: analysis
        uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6
      - name: upload
        uses: github/codeql-action/upload-sarif@76bf77db0b4f84ce3351e7dccabb79e3e2aa8ad3
        with:
          sarif_file: devskim-results.sarif
