name: devskim
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 37 7 * * 3
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  devskim:
    name: devskim
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: analysis
        uses: microsoft/DevSkim-Action@a6b6966a33b497cd3ae2ebc406edf8f4cc2feec6
      - name: upload
        uses: github/codeql-action/upload-sarif@f15aac3db1ec04fd9a69b2b3904f28e913b50c78
        with:
          sarif_file: devskim-results.sarif
