jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
      - name: trunk
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b
name: lint
"on":
  pull_request: null
  push: null
permissions:
  checks: write
  contents: read
  pull-requests: write
