jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: trunk
        uses: trunk-io/trunk-action@75699af9e26881e564e9d832ef7dc3af25ec031b
name: lint
"on":
  pull_request: null
  push: null
permissions:
  checks: write
  contents: read
  pull-requests: write
