name: osv

permissions:
  actions: read
  security-events: write
  contents: read

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * *

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  osv-push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@279b38d966019b3d86b360e97974121318b3e5e8" # v2.0.0-beta2
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
  osv-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@279b38d966019b3d86b360e97974121318b3e5e8" # v2.0.0-beta2
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        --skip-git
        ./
