name: test
permissions: read-all
on:
  push: null
  pull_request: null
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true
      - name: test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          fail_ci_if_error: false
